[versions]
plugin-yml = "0.8.0"
ormlite = "6.1"
guice = "5.1.0"
lamp = "4.0.0-rc.14"

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }
plugin-yml-bukkit = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "plugin-yml" }
run-server = { id = "org.bxteam.runserver", version = "1.2.2" }
quark = { id = "org.bxteam.quark", version = "1.3.0" }

[libraries]
paper = { module = "com.destroystokyo.paper:paper-api", version = "1.16.5-R0.1-SNAPSHOT" }
paperlib = { module = "io.papermc:paperlib", version = "1.0.8" }

helix = { module = "org.bxteam:helix", version = "1.0.0" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version = "3.9.11" }

ormlite = { module = "com.j256.ormlite:ormlite-core", version.ref = "ormlite" }
ormlite-jdbc = { module = "com.j256.ormlite:ormlite-jdbc", version.ref = "ormlite" }
hikari = { module = "com.zaxxer:HikariCP", version = "7.0.2" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version = "3.5.6" }

placeholderapi = { module = "me.clip:placeholderapi", version = "2.11.7" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.42" }

guice = { module = "com.google.inject:guice", version.ref = "guice" }
guice-assistedinject = { module = "com.google.inject.extensions:guice-assistedinject", version.ref = "guice" }

lamp-common = { module = "io.github.revxrsal:lamp.common", version.ref = "lamp" }
lamp-bukkit = { module = "io.github.revxrsal:lamp.bukkit", version.ref = "lamp" }

[bundles]
ormlite = [
    "ormlite",
    "ormlite-jdbc"
]

guice = [
    "guice",
    "guice-assistedinject"
]

lamp = [
    "lamp-common",
    "lamp-bukkit"
]
